name: Basic Workflow
on: workflow_dispatch
env:
  GLOBAL_VARIABLES: "Something just like this"
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Using github actions
        uses: actions/checkout@v3
      - name: Hello World 
        run: 
              echo "Hello World"
      - name: Hello Github
        run: |
              echo "Hello Github"
              echo "This is for multiple-line shell commands"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Global Variables
        run:
              echo $env:GLOBAL_VARIABLES
      
              
